name: route_race_condition_example
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.12.0
  jaspr_router: ^0.4.1

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.0.9
  jaspr_builder: ^0.12.0
  lints: ^3.0.0


jaspr:
  mode: static

